<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Country;
use DB;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        DB::table('countries')->truncate();

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $chunks = array_chunk($this->countriesList(), 100);

        foreach ($chunks as $chunk) {
            Country::upsert(
                $chunk,
                ['iso'],
                ['name_en', 'name_ar', 'name_ur', 'iso_code', 'is_active'],
            );
        }

    }

    private function countriesList(): array
    {
        return [
            ['name_en' => 'Saudi Arabia', 'name_ar' => 'المملكة العربية السعودية', 'name_ur' => 'سعودی عرب', 'iso_code' => 'SA', 'is_active' => true],
            ['name_en' => 'Afghanistan', 'name_ar' => 'أفغانستان', 'name_ur' => 'افغانستان', 'iso_code' => 'AF', 'is_active' => false],
            ['name_en' => 'Albania', 'name_ar' => 'ألبانيا', 'name_ur' => 'البانیہ', 'iso_code' => 'AL', 'is_active' => false],
            ['name_en' => 'Algeria', 'name_ar' => 'الجزائر', 'name_ur' => 'الجزائر', 'iso_code' => 'DZ', 'is_active' => false],
            ['name_en' => 'American Samoa', 'name_ar' => 'ساموا الأمريكية', 'name_ur' => 'امریکی ساموا', 'iso_code' => 'AS', 'is_active' => false],
            ['name_en' => 'Andorra', 'name_ar' => 'أندورا', 'name_ur' => 'انڈورا', 'iso_code' => 'AD', 'is_active' => false],
            ['name_en' => 'Angola', 'name_ar' => 'أنغولا', 'name_ur' => 'انگولا', 'iso_code' => 'AO', 'is_active' => false],
            ['name_en' => 'Anguilla', 'name_ar' => 'أنغيلا', 'name_ur' => 'اینگویلا', 'iso_code' => 'AI', 'is_active' => false],
            ['name_en' => 'Antarctica', 'name_ar' => 'أنتاركتيكا', 'name_ur' => 'انٹارکٹیکا', 'iso_code' => 'AQ', 'is_active' => false],
            ['name_en' => 'Antigua and Barbuda', 'name_ar' => 'أنتيغوا وبربودا', 'name_ur' => 'اینٹیگوا اور باربوڈا', 'iso_code' => 'AG', 'is_active' => false],
            ['name_en' => 'Argentina', 'name_ar' => 'الأرجنتين', 'name_ur' => 'ارجنٹائن', 'iso_code' => 'AR', 'is_active' => false],
            ['name_en' => 'Armenia', 'name_ar' => 'أرمينيا', 'name_ur' => 'آرمینیا', 'iso_code' => 'AM', 'is_active' => false],
            ['name_en' => 'Aruba', 'name_ar' => 'أروبا', 'name_ur' => 'اروبا', 'iso_code' => 'AW', 'is_active' => false],
            ['name_en' => 'Australia', 'name_ar' => 'أستراليا', 'name_ur' => 'آسٹریلیا', 'iso_code' => 'AU', 'is_active' => false],
            ['name_en' => 'Austria', 'name_ar' => 'النمسا', 'name_ur' => 'آسٹریا', 'iso_code' => 'AT', 'is_active' => false],
            ['name_en' => 'Azerbaijan', 'name_ar' => 'أذربيجان', 'name_ur' => 'آذربائیجان', 'iso_code' => 'AZ', 'is_active' => false],
            ['name_en' => 'Bahamas', 'name_ar' => 'جزر البهاما', 'name_ur' => 'باہاماس', 'iso_code' => 'BS', 'is_active' => false],
            ['name_en' => 'Bahrain', 'name_ar' => 'البحرين', 'name_ur' => 'بحرین', 'iso_code' => 'BH', 'is_active' => false],
            ['name_en' => 'Bangladesh', 'name_ar' => 'بنغلاديش', 'name_ur' => 'بنگلہ دیش', 'iso_code' => 'BD', 'is_active' => false],
            ['name_en' => 'Barbados', 'name_ar' => 'بربادوس', 'name_ur' => 'بارباڈوس', 'iso_code' => 'BB', 'is_active' => false],
            ['name_en' => 'Belarus', 'name_ar' => 'بيلاروس', 'name_ur' => 'بیلاروس', 'iso_code' => 'BY', 'is_active' => false],
            ['name_en' => 'Belgium', 'name_ar' => 'بلجيكا', 'name_ur' => 'بیلجیم', 'iso_code' => 'BE', 'is_active' => false],
            ['name_en' => 'Belize', 'name_ar' => 'بليز', 'name_ur' => 'بیلیز', 'iso_code' => 'BZ', 'is_active' => false],
            ['name_en' => 'Benin', 'name_ar' => 'بنين', 'name_ur' => 'بینن', 'iso_code' => 'BJ', 'is_active' => false],
            ['name_en' => 'Bermuda', 'name_ar' => 'برمودا', 'name_ur' => 'برمودا', 'iso_code' => 'BM', 'is_active' => false],
            ['name_en' => 'Bhutan', 'name_ar' => 'بوتان', 'name_ur' => 'بھوٹان', 'iso_code' => 'BT', 'is_active' => false],
            ['name_en' => 'Bolivia', 'name_ar' => 'بوليفيا', 'name_ur' => 'بولیویا', 'iso_code' => 'BO', 'is_active' => false],
            ['name_en' => 'Bosnia and Herzegovina', 'name_ar' => 'البوسنة والهرسك', 'name_ur' => 'بوسنیا اور ہرزیگووینا', 'iso_code' => 'BA', 'is_active' => false],
            ['name_en' => 'Botswana', 'name_ar' => 'بوتسوانا', 'name_ur' => 'بوٹسوانا', 'iso_code' => 'BW', 'is_active' => false],
            ['name_en' => 'Brazil', 'name_ar' => 'البرازيل', 'name_ur' => 'برازیل', 'iso_code' => 'BR', 'is_active' => false],
            ['name_en' => 'British Indian Ocean Territory', 'name_ar' => 'إقليم المحيط الهندي البريطاني', 'name_ur' => 'برطانوی بحر ہند کا علاقہ', 'iso_code' => 'IO', 'is_active' => false],
            ['name_en' => 'British Virgin Islands', 'name_ar' => 'جزر العذراء البريطانية', 'name_ur' => 'برطانوی ورجن جزائر', 'iso_code' => 'VG', 'is_active' => false],
            ['name_en' => 'Brunei', 'name_ar' => 'بروناي', 'name_ur' => 'برونائی', 'iso_code' => 'BN', 'is_active' => false],
            ['name_en' => 'Bulgaria', 'name_ar' => 'بلغاريا', 'name_ur' => 'بلغاریہ', 'iso_code' => 'BG', 'is_active' => false],
            ['name_en' => 'Burkina Faso', 'name_ar' => 'بوركينا فاسو', 'name_ur' => 'برکینا فاسو', 'iso_code' => 'BF', 'is_active' => false],
            ['name_en' => 'Burundi', 'name_ar' => 'بوروندي', 'name_ur' => 'برونڈی', 'iso_code' => 'BI', 'is_active' => false],
            ['name_en' => 'Cambodia', 'name_ar' => 'كمبوديا', 'name_ur' => 'کمبوڈیا', 'iso_code' => 'KH', 'is_active' => false],
            ['name_en' => 'Cameroon', 'name_ar' => 'الكاميرون', 'name_ur' => 'کیمرون', 'iso_code' => 'CM', 'is_active' => false],
            ['name_en' => 'Canada', 'name_ar' => 'كندا', 'name_ur' => 'کینیڈا', 'iso_code' => 'CA', 'is_active' => false],
            ['name_en' => 'Cape Verde', 'name_ar' => 'الرأس الأخضر', 'name_ur' => 'کیپ وردے', 'iso_code' => 'CV', 'is_active' => false],
            ['name_en' => 'Cayman Islands', 'name_ar' => 'جزر كايمان', 'name_ur' => 'کیمین جزائر', 'iso_code' => 'KY', 'is_active' => false],
            ['name_en' => 'Central African Republic', 'name_ar' => 'جمهورية أفريقيا الوسطى', 'name_ur' => 'وسطی افریقی جمہوریہ', 'iso_code' => 'CF', 'is_active' => false],
            ['name_en' => 'Chad', 'name_ar' => 'تشاد', 'name_ur' => 'چاڈ', 'iso_code' => 'TD', 'is_active' => false],
            ['name_en' => 'Chile', 'name_ar' => 'تشيلي', 'name_ur' => 'چلی', 'iso_code' => 'CL', 'is_active' => false],
            ['name_en' => 'China', 'name_ar' => 'الصين', 'name_ur' => 'چین', 'iso_code' => 'CN', 'is_active' => false],
            ['name_en' => 'Christmas Island', 'name_ar' => 'جزيرة عيد الميلاد', 'name_ur' => 'کرسمس جزیرہ', 'iso_code' => 'CX', 'is_active' => false],
            ['name_en' => 'Cocos Islands', 'name_ar' => 'جزر كوكوس', 'name_ur' => 'کوکوس جزائر', 'iso_code' => 'CC', 'is_active' => false],
            ['name_en' => 'Colombia', 'name_ar' => 'كولومبيا', 'name_ur' => 'کولمبیا', 'iso_code' => 'CO', 'is_active' => false],
            ['name_en' => 'Comoros', 'name_ar' => 'جزر القمر', 'name_ur' => 'کوموروس', 'iso_code' => 'KM', 'is_active' => false],
            ['name_en' => 'Congo', 'name_ar' => 'الكونغو', 'name_ur' => 'کانگو', 'iso_code' => 'CG', 'is_active' => false],
            ['name_en' => 'Congo, Democratic Republic of the', 'name_ar' => 'جمهورية الكونغو الديمقراطية', 'name_ur' => 'جمہوری جمہوریہ کانگو', 'iso_code' => 'CD', 'is_active' => false],
            ['name_en' => 'Cook Islands', 'name_ar' => 'جزر كوك', 'name_ur' => 'کک جزائر', 'iso_code' => 'CK', 'is_active' => false],
            ['name_en' => 'Costa Rica', 'name_ar' => 'كوستاريكا', 'name_ur' => 'کوسٹا ریکا', 'iso_code' => 'CR', 'is_active' => false],
            ['name_en' => 'Croatia', 'name_ar' => 'كرواتيا', 'name_ur' => 'کروشیا', 'iso_code' => 'HR', 'is_active' => false],
            ['name_en' => 'Cuba', 'name_ar' => 'كوبا', 'name_ur' => 'کیوبا', 'iso_code' => 'CU', 'is_active' => false],
            ['name_en' => 'Curacao', 'name_ar' => 'كوراساو', 'name_ur' => 'کوراکاؤ', 'iso_code' => 'CW', 'is_active' => false],
            ['name_en' => 'Cyprus', 'name_ar' => 'قبرص', 'name_ur' => 'قبرص', 'iso_code' => 'CY', 'is_active' => false],
            ['name_en' => 'Czech Republic', 'name_ar' => 'جمهورية التشيك', 'name_ur' => 'چیک جمہوریہ', 'iso_code' => 'CZ', 'is_active' => false],
            ['name_en' => 'Denmark', 'name_ar' => 'الدنمارك', 'name_ur' => 'ڈنمارک', 'iso_code' => 'DK', 'is_active' => false],
            ['name_en' => 'Djibouti', 'name_ar' => 'جيبوتي', 'name_ur' => 'جبوتی', 'iso_code' => 'DJ', 'is_active' => false],
            ['name_en' => 'Dominica', 'name_ar' => 'دومينيكا', 'name_ur' => 'ڈومینیکا', 'iso_code' => 'DM', 'is_active' => false],
            ['name_en' => 'Dominican Republic', 'name_ar' => 'جمهورية الدومينيكان', 'name_ur' => 'ڈومینیکن جمہوریہ', 'iso_code' => 'DO', 'is_active' => false],
            ['name_en' => 'East Timor', 'name_ar' => 'تيمور الشرقية', 'name_ur' => 'مشرقی تیمور', 'iso_code' => 'TL', 'is_active' => false],
            ['name_en' => 'Ecuador', 'name_ar' => 'الإكوادور', 'name_ur' => 'ایکواڈور', 'iso_code' => 'EC', 'is_active' => false],
            ['name_en' => 'Egypt', 'name_ar' => 'مصر', 'name_ur' => 'مصر', 'iso_code' => 'EG', 'is_active' => false],
            ['name_en' => 'El Salvador', 'name_ar' => 'السلفادور', 'name_ur' => 'ایل سلواڈور', 'iso_code' => 'SV', 'is_active' => false],
            ['name_en' => 'Equatorial Guinea', 'name_ar' => 'غينيا الاستوائية', 'name_ur' => 'استوائی گنی', 'iso_code' => 'GQ', 'is_active' => false],
            ['name_en' => 'Eritrea', 'name_ar' => 'إريتريا', 'name_ur' => 'اریٹیریا', 'iso_code' => 'ER', 'is_active' => false],
            ['name_en' => 'Estonia', 'name_ar' => 'إستونيا', 'name_ur' => 'ایسٹونیا', 'iso_code' => 'EE', 'is_active' => false],
            ['name_en' => 'Ethiopia', 'name_ar' => 'إثيوبيا', 'name_ur' => 'ایتھوپیا', 'iso_code' => 'ET', 'is_active' => false],
            ['name_en' => 'Falkland Islands', 'name_ar' => 'جزر فوكلاند', 'name_ur' => 'فاک لینڈ جزائر', 'iso_code' => 'FK', 'is_active' => false],
            ['name_en' => 'Faroe Islands', 'name_ar' => 'جزر فارو', 'name_ur' => 'فیرو جزائر', 'iso_code' => 'FO', 'is_active' => false],
            ['name_en' => 'Fiji', 'name_ar' => 'فيجي', 'name_ur' => 'فجی', 'iso_code' => 'FJ', 'is_active' => false],
            ['name_en' => 'Finland', 'name_ar' => 'فنلندا', 'name_ur' => 'فن لینڈ', 'iso_code' => 'FI', 'is_active' => false],
            ['name_en' => 'France', 'name_ar' => 'فرنسا', 'name_ur' => 'فرانس', 'iso_code' => 'FR', 'is_active' => false],
            ['name_en' => 'French Guiana', 'name_ar' => 'غيانا الفرنسية', 'name_ur' => 'فرانسیسی گیانا', 'iso_code' => 'GF', 'is_active' => false],
            ['name_en' => 'French Polynesia', 'name_ar' => 'بولينيزيا الفرنسية', 'name_ur' => 'فرانسیسی پولینیشیا', 'iso_code' => 'PF', 'is_active' => false],
            ['name_en' => 'Gabon', 'name_ar' => 'الغابون', 'name_ur' => 'گیبون', 'iso_code' => 'GA', 'is_active' => false],
            ['name_en' => 'Gambia', 'name_ar' => 'غامبيا', 'name_ur' => 'گیمبیا', 'iso_code' => 'GM', 'is_active' => false],
            ['name_en' => 'Georgia', 'name_ar' => 'جورجيا', 'name_ur' => 'جارجیا', 'iso_code' => 'GE', 'is_active' => false],
            ['name_en' => 'Germany', 'name_ar' => 'ألمانيا', 'name_ur' => 'جرمنی', 'iso_code' => 'DE', 'is_active' => false],
            ['name_en' => 'Ghana', 'name_ar' => 'غانا', 'name_ur' => 'گھانا', 'iso_code' => 'GH', 'is_active' => false],
            ['name_en' => 'Gibraltar', 'name_ar' => 'جبل طارق', 'name_ur' => 'جبل الطارق', 'iso_code' => 'GI', 'is_active' => false],
            ['name_en' => 'Greece', 'name_ar' => 'اليونان', 'name_ur' => 'یونان', 'iso_code' => 'GR', 'is_active' => false],
            ['name_en' => 'Greenland', 'name_ar' => 'جرينلاند', 'name_ur' => 'گرین لینڈ', 'iso_code' => 'GL', 'is_active' => false],
            ['name_en' => 'Grenada', 'name_ar' => 'غرينادا', 'name_ur' => 'گریناڈا', 'iso_code' => 'GD', 'is_active' => false],
            ['name_en' => 'Guadeloupe', 'name_ar' => 'جوادلوب', 'name_ur' => 'گواڈیلوپ', 'iso_code' => 'GP', 'is_active' => false],
            ['name_en' => 'Guam', 'name_ar' => 'غوام', 'name_ur' => 'گوام', 'iso_code' => 'GU', 'is_active' => false],
            ['name_en' => 'Guatemala', 'name_ar' => 'غواتيمالا', 'name_ur' => 'گواتیمالا', 'iso_code' => 'GT', 'is_active' => false],
            ['name_en' => 'Guinea', 'name_ar' => 'غينيا', 'name_ur' => 'گنی', 'iso_code' => 'GN', 'is_active' => false],
            ['name_en' => 'Guinea-Bissau', 'name_ar' => 'غينيا بيساو', 'name_ur' => 'گنی بساؤ', 'iso_code' => 'GW', 'is_active' => false],
            ['name_en' => 'Guyana', 'name_ar' => 'غيانا', 'name_ur' => 'گیانا', 'iso_code' => 'GY', 'is_active' => false],
            ['name_en' => 'Haiti', 'name_ar' => 'هايتي', 'name_ur' => 'ہیٹی', 'iso_code' => 'HT', 'is_active' => false],
            ['name_en' => 'Honduras', 'name_ar' => 'هندوراس', 'name_ur' => 'ہونڈوراس', 'iso_code' => 'HN', 'is_active' => false],
            ['name_en' => 'Hong Kong', 'name_ar' => 'هونغ كونغ', 'name_ur' => 'ہانگ کانگ', 'iso_code' => 'HK', 'is_active' => false],
            ['name_en' => 'Hungary', 'name_ar' => 'هنغاريا', 'name_ur' => 'ہنگری', 'iso_code' => 'HU', 'is_active' => false],
            ['name_en' => 'Iceland', 'name_ar' => 'آيسلندا', 'name_ur' => 'آئس لینڈ', 'iso_code' => 'IS', 'is_active' => false],
            ['name_en' => 'India', 'name_ar' => 'الهند', 'name_ur' => 'بھارت', 'iso_code' => 'IN', 'is_active' => false],
            ['name_en' => 'Indonesia', 'name_ar' => 'إندونيسيا', 'name_ur' => 'انڈونیشیا', 'iso_code' => 'ID', 'is_active' => false],
            ['name_en' => 'Iran', 'name_ar' => 'إيران', 'name_ur' => 'ایران', 'iso_code' => 'IR', 'is_active' => false],
            ['name_en' => 'Iraq', 'name_ar' => 'العراق', 'name_ur' => 'عراق', 'iso_code' => 'IQ', 'is_active' => false],
            ['name_en' => 'Ireland', 'name_ar' => 'أيرلندا', 'name_ur' => 'آئرلینڈ', 'iso_code' => 'IE', 'is_active' => false],
            ['name_en' => 'Isle of Man', 'name_ar' => 'جزيرة مان', 'name_ur' => 'آئل آف مین', 'iso_code' => 'IM', 'is_active' => false],
            ['name_en' => 'Italy', 'name_ar' => 'إيطاليا', 'name_ur' => 'اٹلی', 'iso_code' => 'IT', 'is_active' => false],
            ['name_en' => 'Ivory Coast', 'name_ar' => 'ساحل العاج', 'name_ur' => 'آئیوری کوسٹ', 'iso_code' => 'CI', 'is_active' => false],
            ['name_en' => 'Jamaica', 'name_ar' => 'جامايكا', 'name_ur' => 'جمیکا', 'iso_code' => 'JM', 'is_active' => false],
            ['name_en' => 'Japan', 'name_ar' => 'اليابان', 'name_ur' => 'جاپان', 'iso_code' => 'JP', 'is_active' => false],
            ['name_en' => 'Jordan', 'name_ar' => 'الأردن', 'name_ur' => 'اردن', 'iso_code' => 'JO', 'is_active' => false],
            ['name_en' => 'Kazakhstan', 'name_ar' => 'كازاخستان', 'name_ur' => 'قازقستان', 'iso_code' => 'KZ', 'is_active' => false],
            ['name_en' => 'Kenya', 'name_ar' => 'كينيا', 'name_ur' => 'کینیا', 'iso_code' => 'KE', 'is_active' => false],
            ['name_en' => 'Kiribati', 'name_ar' => 'كيريباتي', 'name_ur' => 'کیریباتی', 'iso_code' => 'KI', 'is_active' => false],
            ['name_en' => 'Kuwait', 'name_ar' => 'الكويت', 'name_ur' => 'کویت', 'iso_code' => 'KW', 'is_active' => false],
            ['name_en' => 'Kyrgyzstan', 'name_ar' => 'قيرغيزستان', 'name_ur' => 'کرغزستان', 'iso_code' => 'KG', 'is_active' => false],
            ['name_en' => 'Laos', 'name_ar' => 'لاوس', 'name_ur' => 'لاؤس', 'iso_code' => 'LA', 'is_active' => false],
            ['name_en' => 'Latvia', 'name_ar' => 'لاتفيا', 'name_ur' => 'لیٹویا', 'iso_code' => 'LV', 'is_active' => false],
            ['name_en' => 'Lebanon', 'name_ar' => 'لبنان', 'name_ur' => 'لبنان', 'iso_code' => 'LB', 'is_active' => false],
            ['name_en' => 'Lesotho', 'name_ar' => 'ليسوتو', 'name_ur' => 'لیسوتھو', 'iso_code' => 'LS', 'is_active' => false],
            ['name_en' => 'Liberia', 'name_ar' => 'ليبيريا', 'name_ur' => 'لائبیریا', 'iso_code' => 'LR', 'is_active' => false],
            ['name_en' => 'Libya', 'name_ar' => 'ليبيا', 'name_ur' => 'لیبیا', 'iso_code' => 'LY', 'is_active' => false],
            ['name_en' => 'Liechtenstein', 'name_ar' => 'ليختنشتاين', 'name_ur' => 'لیختینستائن', 'iso_code' => 'LI', 'is_active' => false],
            ['name_en' => 'Lithuania', 'name_ar' => 'ليتوانيا', 'name_ur' => 'لتھوانیا', 'iso_code' => 'LT', 'is_active' => false],
            ['name_en' => 'Luxembourg', 'name_ar' => 'لوكسمبورغ', 'name_ur' => 'لکسمبرگ', 'iso_code' => 'LU', 'is_active' => false],
            ['name_en' => 'Macao', 'name_ar' => 'ماكاو', 'name_ur' => 'مکاؤ', 'iso_code' => 'MO', 'is_active' => false],
            ['name_en' => 'Macedonia', 'name_ar' => 'مقدونيا', 'name_ur' => 'مقدونیہ', 'iso_code' => 'MK', 'is_active' => false],
            ['name_en' => 'Madagascar', 'name_ar' => 'مدغشقر', 'name_ur' => 'مڈغاسکر', 'iso_code' => 'MG', 'is_active' => false],
            ['name_en' => 'Malawi', 'name_ar' => 'مالاوي', 'name_ur' => 'ملاوی', 'iso_code' => 'MW', 'is_active' => false],
            ['name_en' => 'Malaysia', 'name_ar' => 'ماليزيا', 'name_ur' => 'ملائیشیا', 'iso_code' => 'MY', 'is_active' => false],
            ['name_en' => 'Maldives', 'name_ar' => 'جزر المالديف', 'name_ur' => 'مالدیپ', 'iso_code' => 'MV', 'is_active' => false],
            ['name_en' => 'Mali', 'name_ar' => 'مالي', 'name_ur' => 'مالی', 'iso_code' => 'ML', 'is_active' => false],
            ['name_en' => 'Malta', 'name_ar' => 'مالطا', 'name_ur' => 'مالٹا', 'iso_code' => 'MT', 'is_active' => false],
            ['name_en' => 'Marshall Islands', 'name_ar' => 'جزر مارشال', 'name_ur' => 'مارشل جزائر', 'iso_code' => 'MH', 'is_active' => false],
            ['name_en' => 'Martinique', 'name_ar' => 'مارتينيك', 'name_ur' => 'مارٹینیک', 'iso_code' => 'MQ', 'is_active' => false],
            ['name_en' => 'Mauritania', 'name_ar' => 'موريتانيا', 'name_ur' => 'موریطانیہ', 'iso_code' => 'MR', 'is_active' => false],
            ['name_en' => 'Mauritius', 'name_ar' => 'موريشيوس', 'name_ur' => 'ماریشس', 'iso_code' => 'MU', 'is_active' => false],
            ['name_en' => 'Mayotte', 'name_ar' => 'مايوت', 'name_ur' => 'مایوٹ', 'iso_code' => 'YT', 'is_active' => false],
            ['name_en' => 'Mexico', 'name_ar' => 'المكسيك', 'name_ur' => 'میکسیکو', 'iso_code' => 'MX', 'is_active' => false],
            ['name_en' => 'Micronesia', 'name_ar' => 'ميكرونيزيا', 'name_ur' => 'مائیکرونیشیا', 'iso_code' => 'FM', 'is_active' => false],
            ['name_en' => 'Moldova', 'name_ar' => 'مولدوفا', 'name_ur' => 'مالدووا', 'iso_code' => 'MD', 'is_active' => false],
            ['name_en' => 'Monaco', 'name_ar' => 'موناكو', 'name_ur' => 'موناکو', 'iso_code' => 'MC', 'is_active' => false],
            ['name_en' => 'Mongolia', 'name_ar' => 'منغوليا', 'name_ur' => 'منگولیا', 'iso_code' => 'MN', 'is_active' => false],
            ['name_en' => 'Montenegro', 'name_ar' => 'الجبل الأسود', 'name_ur' => 'مونٹی نیگرو', 'iso_code' => 'ME', 'is_active' => false],
            ['name_en' => 'Montserrat', 'name_ar' => 'مونتسيرات', 'name_ur' => 'مونٹسیراٹ', 'iso_code' => 'MS', 'is_active' => false],
            ['name_en' => 'Morocco', 'name_ar' => 'المغرب', 'name_ur' => 'مراکش', 'iso_code' => 'MA', 'is_active' => false],
            ['name_en' => 'Mozambique', 'name_ar' => 'موزمبيق', 'name_ur' => 'موزمبیق', 'iso_code' => 'MZ', 'is_active' => false],
            ['name_en' => 'Myanmar', 'name_ar' => 'ميانمار', 'name_ur' => 'میانمار', 'iso_code' => 'MM', 'is_active' => false],
            ['name_en' => 'Namibia', 'name_ar' => 'ناميبيا', 'name_ur' => 'نمیبیا', 'iso_code' => 'NA', 'is_active' => false],
            ['name_en' => 'Nauru', 'name_ar' => 'ناورو', 'name_ur' => 'ناورو', 'iso_code' => 'NR', 'is_active' => false],
            ['name_en' => 'Nepal', 'name_ar' => 'نيبال', 'name_ur' => 'نیپال', 'iso_code' => 'NP', 'is_active' => false],
            ['name_en' => 'Netherlands', 'name_ar' => 'هولندا', 'name_ur' => 'نیدرلینڈز', 'iso_code' => 'NL', 'is_active' => false],
            ['name_en' => 'Netherlands Antilles', 'name_ar' => 'جزر الأنتيل الهولندية', 'name_ur' => 'نیدرلینڈز انٹیلیز', 'iso_code' => 'AN', 'is_active' => false],
            ['name_en' => 'New Caledonia', 'name_ar' => 'كاليدونيا الجديدة', 'name_ur' => 'نیو کیلیڈونیا', 'iso_code' => 'NC', 'is_active' => false],
            ['name_en' => 'New Zealand', 'name_ar' => 'نيوزيلندا', 'name_ur' => 'نیوزی لینڈ', 'iso_code' => 'NZ', 'is_active' => false],
            ['name_en' => 'Nicaragua', 'name_ar' => 'نيكاراغوا', 'name_ur' => 'نکاراگوا', 'iso_code' => 'NI', 'is_active' => false],
            ['name_en' => 'Niger', 'name_ar' => 'النيجر', 'name_ur' => 'نائجر', 'iso_code' => 'NE', 'is_active' => false],
            ['name_en' => 'Nigeria', 'name_ar' => 'نيجيريا', 'name_ur' => 'نائجیریا', 'iso_code' => 'NG', 'is_active' => false],
            ['name_en' => 'Niue', 'name_ar' => 'نيوي', 'name_ur' => 'نیوئے', 'iso_code' => 'NU', 'is_active' => false],
            ['name_en' => 'Norfolk Island', 'name_ar' => 'جزيرة نورفولك', 'name_ur' => 'نارفولک جزیرہ', 'iso_code' => 'NF', 'is_active' => false],
            ['name_en' => 'North Korea', 'name_ar' => 'كوريا الشمالية', 'name_ur' => 'شمالی کوریا', 'iso_code' => 'KP', 'is_active' => false],
            ['name_en' => 'Northern Cyprus', 'name_ar' => 'قبرص الشمالية', 'name_ur' => 'شمالی قبرص', 'iso_code' => 'NC', 'is_active' => false],
            ['name_en' => 'Norway', 'name_ar' => 'النرويج', 'name_ur' => 'ناروے', 'iso_code' => 'NO', 'is_active' => false],
            ['name_en' => 'Oman', 'name_ar' => 'عُمان', 'name_ur' => 'عمان', 'iso_code' => 'OM', 'is_active' => false],
            ['name_en' => 'Pakistan', 'name_ar' => 'باكستان', 'name_ur' => 'پاکستان', 'iso_code' => 'PK', 'is_active' => false],
            ['name_en' => 'Palau', 'name_ar' => 'بالاو', 'name_ur' => 'پلاؤ', 'iso_code' => 'PW', 'is_active' => false],
            ['name_en' => 'Palestine', 'name_ar' => 'فلسطين', 'name_ur' => 'فلسطین', 'iso_code' => 'PS', 'is_active' => false],
            ['name_en' => 'Panama', 'name_ar' => 'بنما', 'name_ur' => 'پاناما', 'iso_code' => 'PA', 'is_active' => false],
            ['name_en' => 'Papua New Guinea', 'name_ar' => 'بابوا غينيا الجديدة', 'name_ur' => 'پاپوا نیو گنی', 'iso_code' => 'PG', 'is_active' => false],
            ['name_en' => 'Paraguay', 'name_ar' => 'باراغواي', 'name_ur' => 'پیراگوئے', 'iso_code' => 'PY', 'is_active' => false],
            ['name_en' => 'Peru', 'name_ar' => 'بيرو', 'name_ur' => 'پیرو', 'iso_code' => 'PE', 'is_active' => false],
            ['name_en' => 'Philippines', 'name_ar' => 'الفلبين', 'name_ur' => 'فلپائن', 'iso_code' => 'PH', 'is_active' => false],
            ['name_en' => 'Pitcairn Islands', 'name_ar' => 'جزر بيتكيرن', 'name_ur' => 'پٹکیرن جزائر', 'iso_code' => 'PN', 'is_active' => false],
            ['name_en' => 'Poland', 'name_ar' => 'بولندا', 'name_ur' => 'پولینڈ', 'iso_code' => 'PL', 'is_active' => false],
            ['name_en' => 'Portugal', 'name_ar' => 'البرتغال', 'name_ur' => 'پرتگال', 'iso_code' => 'PT', 'is_active' => false],
            ['name_en' => 'Puerto Rico', 'name_ar' => 'بورتوريكو', 'name_ur' => 'پورٹو ریکو', 'iso_code' => 'PR', 'is_active' => false],
            ['name_en' => 'Qatar', 'name_ar' => 'قطر', 'name_ur' => 'قطر', 'iso_code' => 'QA', 'is_active' => false],
            ['name_en' => 'Romania', 'name_ar' => 'رومانيا', 'name_ur' => 'رومانیہ', 'iso_code' => 'RO', 'is_active' => false],
            ['name_en' => 'Russia', 'name_ar' => 'روسيا', 'name_ur' => 'روس', 'iso_code' => 'RU', 'is_active' => false],
            ['name_en' => 'Rwanda', 'name_ar' => 'رواندا', 'name_ur' => 'روانڈا', 'iso_code' => 'RW', 'is_active' => false],
            ['name_en' => 'Saint Barthelemy', 'name_ar' => 'سانت بارتيليمي', 'name_ur' => 'سینٹ بارتھلیمی', 'iso_code' => 'BL', 'is_active' => false],
            ['name_en' => 'Saint Helena', 'name_ar' => 'سانت هيلينا', 'name_ur' => 'سینٹ ہیلینا', 'iso_code' => 'SH', 'is_active' => false],
            ['name_en' => 'Saint Kitts and Nevis', 'name_ar' => 'سانت كيتس ونيفيس', 'name_ur' => 'سینٹ کیٹس اور نیوس', 'iso_code' => 'KN', 'is_active' => false],
            ['name_en' => 'Saint Lucia', 'name_ar' => 'سانت لوسيا', 'name_ur' => 'سینٹ لوسیا', 'iso_code' => 'LC', 'is_active' => false],
            ['name_en' => 'Saint Martin', 'name_ar' => 'سانت مارتن', 'name_ur' => 'سینٹ مارٹن', 'iso_code' => 'MF', 'is_active' => false],
            ['name_en' => 'Saint Pierre and Miquelon', 'name_ar' => 'سان بيير وميكلون', 'name_ur' => 'سینٹ پیئر اور مائیکلون', 'iso_code' => 'PM', 'is_active' => false],
            ['name_en' => 'Saint Vincent and the Grenadines', 'name_ar' => 'سانت فنسنت والغرينادين', 'name_ur' => 'سینٹ ونسنٹ اور گریناڈائنز', 'iso_code' => 'VC', 'is_active' => false],
            ['name_en' => 'Samoa', 'name_ar' => 'ساموا', 'name_ur' => 'ساموا', 'iso_code' => 'WS', 'is_active' => false],
            ['name_en' => 'San Marino', 'name_ar' => 'سان مارينو', 'name_ur' => 'سان مارینو', 'iso_code' => 'SM', 'is_active' => false],
            ['name_en' => 'Sao Tome and Principe', 'name_ar' => 'ساو تومي وبرينسيبي', 'name_ur' => 'ساؤ ٹومے اور پرنسپے', 'iso_code' => 'ST', 'is_active' => false],
            ['name_en' => 'Senegal', 'name_ar' => 'السنغال', 'name_ur' => 'سینیگال', 'iso_code' => 'SN', 'is_active' => false],
            ['name_en' => 'Serbia', 'name_ar' => 'صربيا', 'name_ur' => 'سربیا', 'iso_code' => 'RS', 'is_active' => false],
            ['name_en' => 'Seychelles', 'name_ar' => 'سيشيل', 'name_ur' => 'سیچلز', 'iso_code' => 'SC', 'is_active' => false],
            ['name_en' => 'Sierra Leone', 'name_ar' => 'سيراليون', 'name_ur' => 'سیرا لیون', 'iso_code' => 'SL', 'is_active' => false],
            ['name_en' => 'Singapore', 'name_ar' => 'سنغافورة', 'name_ur' => 'سنگاپور', 'iso_code' => 'SG', 'is_active' => false],
            ['name_en' => 'Sint Maarten', 'name_ar' => 'سينت مارتن', 'name_ur' => 'سینٹ مارٹن', 'iso_code' => 'SX', 'is_active' => false],
            ['name_en' => 'Slovakia', 'name_ar' => 'سلوفاكيا', 'name_ur' => 'سلوواکیہ', 'iso_code' => 'SK', 'is_active' => false],
            ['name_en' => 'Slovenia', 'name_ar' => 'سلوفينيا', 'name_ur' => 'سلووینیا', 'iso_code' => 'SI', 'is_active' => false],
            ['name_en' => 'Solomon Islands', 'name_ar' => 'جزر سليمان', 'name_ur' => 'سولومن جزائر', 'iso_code' => 'SB', 'is_active' => false],
            ['name_en' => 'Somalia', 'name_ar' => 'الصومال', 'name_ur' => 'صومالیہ', 'iso_code' => 'SO', 'is_active' => false],
            ['name_en' => 'South Africa', 'name_ar' => 'جنوب أفريقيا', 'name_ur' => 'جنوبی افریقہ', 'iso_code' => 'ZA', 'is_active' => false],
            ['name_en' => 'South Korea', 'name_ar' => 'كوريا الجنوبية', 'name_ur' => 'جنوبی کوریا', 'iso_code' => 'KR', 'is_active' => false],
            ['name_en' => 'South Ossetia', 'name_ar' => 'أوسيتيا الجنوبية', 'name_ur' => 'جنوبی اوسیتیا', 'iso_code' => 'SO', 'is_active' => false],
            ['name_en' => 'South Sudan', 'name_ar' => 'جنوب السودان', 'name_ur' => 'جنوبی سوڈان', 'iso_code' => 'SS', 'is_active' => false],
            ['name_en' => 'Spain', 'name_ar' => 'إسبانيا', 'name_ur' => 'سپین', 'iso_code' => 'ES', 'is_active' => false],
            ['name_en' => 'Sri Lanka', 'name_ar' => 'سريلانكا', 'name_ur' => 'سری لنکا', 'iso_code' => 'LK', 'is_active' => false],
            ['name_en' => 'Sudan', 'name_ar' => 'السودان', 'name_ur' => 'سوڈان', 'iso_code' => 'SD', 'is_active' => false],
            ['name_en' => 'Suriname', 'name_ar' => 'سورينام', 'name_ur' => 'سورینام', 'iso_code' => 'SR', 'is_active' => false],
            ['name_en' => 'Swaziland', 'name_ar' => 'سوازيلاند', 'name_ur' => 'سوازی لینڈ', 'iso_code' => 'SZ', 'is_active' => false],
            ['name_en' => 'Sweden', 'name_ar' => 'السويد', 'name_ur' => 'سویڈن', 'iso_code' => 'SE', 'is_active' => false],
            ['name_en' => 'Switzerland', 'name_ar' => 'سويسرا', 'name_ur' => 'سوئٹزرلینڈ', 'iso_code' => 'CH', 'is_active' => false],
            ['name_en' => 'Syria', 'name_ar' => 'سوريا', 'name_ur' => 'شام', 'iso_code' => 'SY', 'is_active' => false],
            ['name_en' => 'Taiwan', 'name_ar' => 'تايوان', 'name_ur' => 'تائیوان', 'iso_code' => 'TW', 'is_active' => false],
            ['name_en' => 'Tajikistan', 'name_ar' => 'طاجيكستان', 'name_ur' => 'تاجکستان', 'iso_code' => 'TJ', 'is_active' => false],
            ['name_en' => 'Tanzania', 'name_ar' => 'تنزانيا', 'name_ur' => 'تنزانیہ', 'iso_code' => 'TZ', 'is_active' => false],
            ['name_en' => 'Thailand', 'name_ar' => 'تايلاند', 'name_ur' => 'تھائی لینڈ', 'iso_code' => 'TH', 'is_active' => false],
            ['name_en' => 'Togo', 'name_ar' => 'توغو', 'name_ur' => 'ٹوگو', 'iso_code' => 'TG', 'is_active' => false],
            ['name_en' => 'Tokelau', 'name_ar' => 'توكيلاو', 'name_ur' => 'ٹوکیلاؤ', 'iso_code' => 'TK', 'is_active' => false],
            ['name_en' => 'Tonga', 'name_ar' => 'تونغا', 'name_ur' => 'ٹونگا', 'iso_code' => 'TO', 'is_active' => false],
            ['name_en' => 'Trinidad and Tobago', 'name_ar' => 'ترينيداد وتوباغو', 'name_ur' => 'ٹرینیڈاڈ اور ٹوباگو', 'iso_code' => 'TT', 'is_active' => false],
            ['name_en' => 'Tunisia', 'name_ar' => 'تونس', 'name_ur' => 'تونس', 'iso_code' => 'TN', 'is_active' => false],
            ['name_en' => 'Turkey', 'name_ar' => 'تركيا', 'name_ur' => 'ترکی', 'iso_code' => 'TR', 'is_active' => false],
            ['name_en' => 'Turkmenistan', 'name_ar' => 'تركمانستان', 'name_ur' => 'ترکمانستان', 'iso_code' => 'TM', 'is_active' => false],
            ['name_en' => 'Turks and Caicos Islands', 'name_ar' => 'جزر تركس وكايكوس', 'name_ur' => 'ترکس اور کائکوس جزائر', 'iso_code' => 'TC', 'is_active' => false],
            ['name_en' => 'Tuvalu', 'name_ar' => 'توفالو', 'name_ur' => 'ٹووالو', 'iso_code' => 'TV', 'is_active' => false],
            ['name_en' => 'Uganda', 'name_ar' => 'أوغندا', 'name_ur' => 'یوگنڈا', 'iso_code' => 'UG', 'is_active' => false],
            ['name_en' => 'Ukraine', 'name_ar' => 'أوكرانيا', 'name_ur' => 'یوکرین', 'iso_code' => 'UA', 'is_active' => false],
            ['name_en' => 'United Arab Emirates', 'name_ar' => 'الإمارات العربية المتحدة', 'name_ur' => 'متحدہ عرب امارات', 'iso_code' => 'AE', 'is_active' => false],
            ['name_en' => 'United Kingdom', 'name_ar' => 'المملكة المتحدة', 'name_ur' => 'مملکت متحدہ', 'iso_code' => 'GB', 'is_active' => false],
            ['name_en' => 'United States', 'name_ar' => 'الولايات المتحدة', 'name_ur' => 'ریاستہائے متحدہ', 'iso_code' => 'US', 'is_active' => false],
            ['name_en' => 'United States Virgin Islands', 'name_ar' => 'جزر العذراء الأمريكية', 'name_ur' => 'ریاستہائے متحدہ ورجن جزائر', 'iso_code' => 'VI', 'is_active' => false],
            ['name_en' => 'Uruguay', 'name_ar' => 'أوروغواي', 'name_ur' => 'یوراگوئے', 'iso_code' => 'UY', 'is_active' => false],
            ['name_en' => 'Uzbekistan', 'name_ar' => 'أوزبكستان', 'name_ur' => 'ازبکستان', 'iso_code' => 'UZ', 'is_active' => false],
            ['name_en' => 'Vanuatu', 'name_ar' => 'فانواتو', 'name_ur' => 'وانواتو', 'iso_code' => 'VU', 'is_active' => false],
            ['name_en' => 'Vatican', 'name_ar' => 'الفاتيكان', 'name_ur' => 'ویٹیکن', 'iso_code' => 'VA', 'is_active' => false],
            ['name_en' => 'Venezuela', 'name_ar' => 'فنزويلا', 'name_ur' => 'وینزویلا', 'iso_code' => 'VE', 'is_active' => false],
            ['name_en' => 'Vietnam', 'name_ar' => 'فيتنام', 'name_ur' => 'ویتنام', 'iso_code' => 'VN', 'is_active' => false],
            ['name_en' => 'Wallis and Futuna', 'name_ar' => 'واليس وفوتونا', 'name_ur' => 'والس اور فوٹونا', 'iso_code' => 'WF', 'is_active' => false],
            ['name_en' => 'Western Sahara', 'name_ar' => 'الصحراء الغربية', 'name_ur' => 'مغربی صحارا', 'iso_code' => 'EH', 'is_active' => false],
            ['name_en' => 'Yemen', 'name_ar' => 'اليمن', 'name_ur' => 'یمن', 'iso_code' => 'YE', 'is_active' => false],
            ['name_en' => 'Zambia', 'name_ar' => 'زامبيا', 'name_ur' => 'زیمبیا', 'iso_code' => 'ZM', 'is_active' => false],
            ['name_en' => 'Zimbabwe', 'name_ar' => 'زيمبابوي', 'name_ur' => 'زمبابوے', 'iso_code' => 'ZW', 'is_active' => false],
            ['name_en' => 'Abkhazia', 'name_ar' => 'أبخازيا', 'name_ur' => 'ابخازیا', 'iso_code' => 'AB', 'is_active' => false],
            ['name_en' => 'Kosovo', 'name_ar' => 'كوسوفو', 'name_ur' => 'کوسوو', 'iso_code' => 'XK', 'is_active' => false],
            ['name_en' => 'South Ossetia', 'name_ar' => 'أوسيتيا الجنوبية', 'name_ur' => 'جنوبی اوسیتیا', 'iso_code' => 'SO', 'is_active' => false],
        ];
    }
}
